# 🛒 E-Commerce Data Processing & Cleaning
**Dataset:** 6 relational tables · ~133K rows · 51 columns · 3.5 years (2023–2026)  
**Author:** Holarbrain | [holarbrain.github.io](https://holarbrain.github.io)  
**Stack:** Python · pandas

---

In [ ]:
import pandas as pd
import os

# List of files to clean
files = [
    '/content/interactions.csv',
    '/content/products.csv',
    '/content/purchases.csv',
    '/content/reviews.csv',
    '/content/sessions.csv',
    '/content/users.csv'
]

def clean_dataset(file_path):
    print(f'Cleaning {file_path}...')
    df = pd.read_csv(file_path)

    # Basic cleaning: remove exact duplicates
    initial_shape = df.shape
    df = df.drop_duplicates()

    # Example: Simple missing value handling (filling numeric with mean, categorical with mode)
    for col in df.columns:
        if df[col].isnull().any():
            if pd.api.types.is_numeric_dtype(df[col]):
                df[col] = df[col].fillna(df[col].mean())
            else:
                df[col] = df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else 'Unknown')

    cleaned_path = file_path.replace('.csv', '_cleaned.csv')
    df.to_csv(cleaned_path, index=False)
    print(f'Done. Saved to {cleaned_path}. Original rows: {initial_shape[0]}, Cleaned rows: {df.shape[0]}')
    return cleaned_path

# Process all files
cleaned_files = [clean_dataset(f) for f in files]

Cleaning /content/interactions.csv...
Done. Saved to /content/interactions_cleaned.csv. Original rows: 100000, Cleaned rows: 100000
Cleaning /content/products.csv...
Done. Saved to /content/products_cleaned.csv. Original rows: 1000, Cleaned rows: 1000
Cleaning /content/purchases.csv...
Done. Saved to /content/purchases_cleaned.csv. Original rows: 1737, Cleaned rows: 1737
Cleaning /content/reviews.csv...
Done. Saved to /content/reviews_cleaned.csv. Original rows: 1253, Cleaned rows: 1253
Cleaning /content/sessions.csv...
Done. Saved to /content/sessions_cleaned.csv. Original rows: 19315, Cleaned rows: 19315
Cleaning /content/users.csv...
Done. Saved to /content/users_cleaned.csv. Original rows: 10000, Cleaned rows: 10000

In [ ]:
# Preview one of the cleaned datasets
if cleaned_files:
    df_preview = pd.read_csv(cleaned_files[0])
    display(df_preview.head())

,interaction_id,user_id,product_id,session_id,interaction_type,timestamp,dwell_time_ms
0,2ece1c7b-3244-4eeb-8d3e-f1b0cc09f20f,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,29:18.0,30481
1,bef097f8-4624-406a-9168-fc16f6d9db7a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,29:50.7,37889
2,131590fb-aded-4eb2-b04a-158540271950,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,b1a8533d-7d06-48ae-b1d2-02a39ad1c623,0003375f-8f69-44e1-9429-ec083de18495,view,30:37.2,11801
3,dda794be-afc4-4b8c-9a5c-3594d513f261,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,b1a8533d-7d06-48ae-b1d2-02a39ad1c623,0003375f-8f69-44e1-9429-ec083de18495,view,30:37.2,11801
4,b68f3af4-29d1-4d85-884a-5e585d5d0a4a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,2ee058a5-f098-4961-a46d-ba699b635b84,0003375f-8f69-44e1-9429-ec083de18495,add_to_wishlist,30:50.2,1404

In [ ]:
print('--- Column Information ---')
print(df_preview.info())

print('\n--- Descriptive Statistics ---')
display(df_preview.describe(include='all'))

--- Column Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   interaction_id    100000 non-null  object
 1   user_id           100000 non-null  object
 2   product_id        100000 non-null  object
 3   session_id        100000 non-null  object
 4   interaction_type  100000 non-null  object
 5   timestamp         100000 non-null  object
 6   dwell_time_ms     100000 non-null  int64
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None

--- Descriptive Statistics ---

,interaction_id,user_id,product_id,session_id,interaction_type,timestamp,dwell_time_ms
count,100000,100000,100000,100000,100000,100000,100000.000000
unique,100000,6944,967,19315,6,32190,NaN
top,ffebb78d-b238-402e-924f-61b780361c67,2603c13e-2c0e-4098-9656-0da109a9dbfb,6e9b539a-77ad-4307-acb5-f558f8b5cc6f,8cf87e9e-9b56-482e-918c-bacf72c93677,view,19:21.0,NaN
freq,1,88,6777,28,50463,20,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,17942.900550
std,NaN,NaN,NaN,NaN,NaN,NaN,21556.684456
min,NaN,NaN,NaN,NaN,NaN,NaN,500.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,4260.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,11153.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,23342.250000
max,NaN,NaN,NaN,NaN,NaN,NaN,300000.000000

In [ ]:
products_df = pd.read_csv('/content/products_cleaned.csv')

# Perform the join on product_id
merged_df = pd.merge(df_preview, products_df, on='product_id', how='inner')

print(f'Joined Data Shape: {merged_df.shape}')
display(merged_df.head())

Joined Data Shape: (100000, 17)

,interaction_id,user_id,product_id,session_id,interaction_type,timestamp,dwell_time_ms,product_name,product_description,category,subcategory,brand,price,rating_avg,review_count,stock_quantity,date_added
0,2ece1c7b-3244-4eeb-8d3e-f1b0cc09f20f,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,29:18.0,30481,Cuisinart Smart Appliance,The Cuisinart Smart Appliance brings both styl...,Home & Kitchen,Appliances,Cuisinart,44.48,4.200000,27,5,2023-08-21
1,bef097f8-4624-406a-9168-fc16f6d9db7a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,29:50.7,37889,Cuisinart Smart Appliance,The Cuisinart Smart Appliance brings both styl...,Home & Kitchen,Appliances,Cuisinart,44.48,4.200000,27,5,2023-08-21
2,131590fb-aded-4eb2-b04a-158540271950,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,b1a8533d-7d06-48ae-b1d2-02a39ad1c623,0003375f-8f69-44e1-9429-ec083de18495,view,30:37.2,11801,"Instant Pot 32"" Kitchenware Set",Elevate your everyday living with the Instant ...,Home & Kitchen,Kitchenware,Instant Pot,50.68,2.500000,2,11,2025-03-01
3,dda794be-afc4-4b8c-9a5c-3594d513f261,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,b1a8533d-7d06-48ae-b1d2-02a39ad1c623,0003375f-8f69-44e1-9429-ec083de18495,view,30:37.2,11801,"Instant Pot 32"" Kitchenware Set",Elevate your everyday living with the Instant ...,Home & Kitchen,Kitchenware,Instant Pot,50.68,2.500000,2,11,2025-03-01
4,b68f3af4-29d1-4d85-884a-5e585d5d0a4a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,2ee058a5-f098-4961-a46d-ba699b635b84,0003375f-8f69-44e1-9429-ec083de18495,add_to_wishlist,30:50.2,1404,L'Oreal Bath & Body Scrub,Transform your daily routine with the L'Oreal ...,Beauty & Personal Care,Bath & Body,L'Oreal,46.25,4.048894,0,1,2024-02-22

In [ ]:
# Fix the warning by specifying a format or handling the partial timestamp correctly
# Note: The 'timestamp' in this dataset appears to be MM:SS.s relative to a session,
# but we will standardize other categorical and date columns across all datasets.

def standardize_df(df):
    # Standardize string columns: lowercase and strip
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].astype(str).str.strip().str.lower()
    return df

# Standardize merged_df
merged_df = standardize_df(merged_df)

# Standardize and structure remaining cleaned datasets
other_datasets = {
    'users': '/content/users_cleaned.csv',
    'purchases': '/content/purchases_cleaned.csv',
    'reviews': '/content/reviews_cleaned.csv',
    'sessions': '/content/sessions_cleaned.csv'
}

structured_dfs = {}
for name, path in other_datasets.items():
    temp_df = pd.read_csv(path)
    temp_df = standardize_df(temp_df)

    # Specific Date conversions where applicable
    date_cols = ['signup_date', 'purchase_date', 'review_date', 'session_start', 'session_end']
    for col in date_cols:
        if col in temp_df.columns:
            temp_df[col] = pd.to_datetime(temp_df[col], errors='coerce')

    temp_df.to_csv(path, index=False)
    structured_dfs[name] = temp_df

print('Standardization and structuring complete for all datasets.')
display(merged_df.head(2))

Standardization and structuring complete for all datasets.

,interaction_id,user_id,product_id,session_id,interaction_type,timestamp,dwell_time_ms,product_name,product_description,category,subcategory,brand,price,rating_avg,review_count,stock_quantity,date_added,interaction_month
0,2ece1c7b-3244-4eeb-8d3e-f1b0cc09f20f,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,29:18.0,30481,cuisinart smart appliance,the cuisinart smart appliance brings both styl...,home & kitchen,appliances,cuisinart,44.48,4.2,27,5,2023-08-21,NaN
1,bef097f8-4624-406a-9168-fc16f6d9db7a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,29:50.7,37889,cuisinart smart appliance,the cuisinart smart appliance brings both styl...,home & kitchen,appliances,cuisinart,44.48,4.2,27,5,2023-08-21,NaN

## Execurive Summary of data processing
We have sucessfully transformed the raw datasets into structured, high_quality, and analysis_ready format. Below is the summary of the operations performed:

**Data Cleaning & Integrity**

**Duplicate Removal**: We processed all six datasets (interactions, products, purchases, reviews, sessions, and users) and removed all exact duplicate rows to ensure data uniqueness.

**Missing Value Handling:** We addressed null values by imputing numerical columns with the mean and categorical columns with the most frequent value (mode), ensuring complete records for all 100,000 interaction entries.
Data Integration

**Unified View:** We performed an inner join between the interactions and products datasets. The resulting merged_df combines user behavior with rich product metadata (brand, category, price, and ratings), expanding the feature set from 7 to 18 columns.
Standardization & Normalization

**Text Formatting:** All string-based categorical data (names, categories, brands) has been normalized to lowercase and trimmed of whitespace for consistent grouping and filtering.

**Temporal Structuring:** Identified date fields across all datasets were converted from strings to formal Python datetime objects to enable accurate time-series analysis.
Dataset Profiling

The cleaned interactions data shows approximately 7,000 unique users interacting with nearly 1,000 unique products.
The most common interaction is the 'view' event, with a typical user engagement (dwell time) averaging around 18 seconds.

---
*Analysis by Holarbrain · github.com/holarbrain*